### ISSUE TITLE
HPC-LAB1

### ISSUE THREAD

**Issue by Xevi8X** [ccfd/courses#103]
@kubagalecki 

W przypadku instalacji biblioteki Benchmark manualnie z repo, cmake z instrukcji nie działa, bo nie wykrywa lokalizacji z Benchmarkiem.

Aby nie instalować biblioteki globalnie wystarczy wywołać:

export CMAKE_PREFIX_PATH= ${CMAKE_PREFIX_PATH}:PATH_TO_LIB/benchmark/build

**Comment by kubagalecki** [comment]
> Aby nie instalować biblioteki globalnie wystarczy wywołać:
> 
> `export CMAKE_PREFIX_PATH= ${CMAKE_PREFIX_PATH}:PATH_TO_LIB/benchmark/build`

Bardziej eleganckim sposobem jest podawanie ścieżki do biblioteki przy konfiguracji:
```bash
cmake -Dbenchmark_DIR="/path/to/benchmark" [other options] ..
```

Dodałem odpowiedni komentarz do instrukcji
